// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.1
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Models
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.1")]
	public partial class Coleta : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""Coleta"",""namespace"":""Models"",""fields"":[{""name"":""DeviceId"",""type"":""string""},{""name"":""Bandeira"",""type"":""string""},{""name"":""ProdutoId"",""type"":""string""},{""name"":""PrecoSite"",""type"":""double""},{""name"":""PrecoDesconto"",""type"":""double""},{""name"":""Sku"",""type"":""string""},{""name"":""Origem"",""type"":""string""},{""name"":""DataEvento"",""type"":""string""}]}");
		private string _DeviceId;
		private string _Bandeira;
		private string _ProdutoId;
		private double _PrecoSite;
		private double _PrecoDesconto;
		private string _Sku;
		private string _Origem;
		private string _DataEvento;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return Coleta._SCHEMA;
			}
		}
		public string DeviceId
		{
			get
			{
				return this._DeviceId;
			}
			set
			{
				this._DeviceId = value;
			}
		}
		public string Bandeira
		{
			get
			{
				return this._Bandeira;
			}
			set
			{
				this._Bandeira = value;
			}
		}
		public string ProdutoId
		{
			get
			{
				return this._ProdutoId;
			}
			set
			{
				this._ProdutoId = value;
			}
		}
		public double PrecoSite
		{
			get
			{
				return this._PrecoSite;
			}
			set
			{
				this._PrecoSite = value;
			}
		}
		public double PrecoDesconto
		{
			get
			{
				return this._PrecoDesconto;
			}
			set
			{
				this._PrecoDesconto = value;
			}
		}
		public string Sku
		{
			get
			{
				return this._Sku;
			}
			set
			{
				this._Sku = value;
			}
		}
		public string Origem
		{
			get
			{
				return this._Origem;
			}
			set
			{
				this._Origem = value;
			}
		}
		public string DataEvento
		{
			get
			{
				return this._DataEvento;
			}
			set
			{
				this._DataEvento = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.DeviceId;
			case 1: return this.Bandeira;
			case 2: return this.ProdutoId;
			case 3: return this.PrecoSite;
			case 4: return this.PrecoDesconto;
			case 5: return this.Sku;
			case 6: return this.Origem;
			case 7: return this.DataEvento;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.DeviceId = (System.String)fieldValue; break;
			case 1: this.Bandeira = (System.String)fieldValue; break;
			case 2: this.ProdutoId = (System.String)fieldValue; break;
			case 3: this.PrecoSite = (System.Double)fieldValue; break;
			case 4: this.PrecoDesconto = (System.Double)fieldValue; break;
			case 5: this.Sku = (System.String)fieldValue; break;
			case 6: this.Origem = (System.String)fieldValue; break;
			case 7: this.DataEvento = (System.String)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
